<p>.Cuando se trata de alternativas lácteas, ya tenemos muchas «leches» para elegir, pero la última alternativa podría cambiar las reglas del juego debido a lo accesible y barato que es su ingrediente principal.

La leche de papa no suena como la cosa más deliciosa del mundo, pero tampoco la leche de avena o la leche de soja, y sin embargo resultaron ser muy populares. Sin mencionar que esta nueva alternativa láctea es aparentemente «deliciosamente cremosa» y funciona muy bien para lattes y capuchinos caseros. Además, la humilde papa utiliza mucha menos tierra y recursos que otras plantas que actualmente se utilizan para la producción de leche, lo que hace que tanto la verdura como la leche sean más accesibles./p>

</p>
